baseurl = ""
title = "Code { for content }"
copyright = "Copyright &copy; 2018 - Richard Ulfvin"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Richard Ulfvin"
    github = "ulfvins"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "ulfvin"
    instagram = ""

[params]
    tagline = "A Hugo theme for creative and technical writing"


